### ISSUE TITLE
Change accuracy of sinus value

### ISSUE THREAD

**Issue by HummelN7872** [industrial-edge/S7-Connector-data-handling-getting-started#1]
The Sinus values is displayed in the Gauge with > 15 decimal places, that's way to many decimal places.
Please change the accuracy to 3 decimal places. [Link](https://github.com/industrial-edge/S7-Connector-data-handling-getting-started#usage)

![Dashboard.PNG](https://github.com/industrial-edge/S7-Connector-data-handling-getting-started/blob/master/docs/graphics/Dashboard.PNG)

**Comment by HummelN7872** [comment]
Please get in contact with Manuel, he knows a possible solution

**Comment by NicoleW11** [comment]
changed the accuracy and adjust the image of the dashboard and the flowCreator.json file
